### ISSUE TITLE
Improve secrets-sync to support custom key naming

### ISSUE THREAD

**Issue by anovikov-el** [edenlabllc/secrets-sync.operators.infra#4]
Example:

```
- name: mongodb
   keys:
      <src_name>: <dst_name>
  src-namespace: mongodb
  dst-namespaces:
    - kafka
    - fhir-server
```
